###
POST http://localhost:8080/soap-api/WeatherSoapService_1.0
Content-Type: application/xml

< GetCityForecastByZIPTest.xml

###
POST http://localhost:8080/soap-api/WeatherSoapService_1.0
Content-Type: application/xml

< xmlerrors/invalid_request.xml
###
POST http://localhost:8080/soap-api/WeatherSoapService_1.0
Content-Type: application/xml

< xmlerrors/xmlErrorNotXmlSchemeCompliantRootElementTest.xml
